//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("ETag Cache")]
[assembly: AssemblyCompany("Illallangi Enterprises")]
[assembly: AssemblyProduct("ETag Cache")]
[assembly: AssemblyCopyright("Copyright © Illallangi Enterprises 2014")]
[assembly: ComVisible(false)]
[assembly: AssemblyInformationalVersion("Debug Build")]
[assembly: Guid("70624027-5085-4cf3-ba58-f478dfa70cdb")]
[assembly: AssemblyVersion("0.0.0.1")]
[assembly: AssemblyFileVersion("0.0.0.1")]


